### PR TITLE
ENH Add CUDA support with miniforge

### PR DESCRIPTION
**Pull request by mike-wendt**
Follows #143 - only `amd64` support in this PR:
- [x] Add `miniforge` support for `amd64` 
- [x] Create images `miniforge-cuda` and to match upstream `nvidia/cuda` and `nvidia/cuda-arm64` respectively
- [x] Update gpuCI scripts and jobs for builds - updated [PRB script](https://gpuci.gpuopenanalytics.com/job/gpuci/job/gpuci-build-environment/job/gpuci-build-environment-prb/jobConfigHistory/showDiffFiles?timestamp1=2020-11-13_10-24-32&timestamp2=2020-12-02_13-30-03)
- [x] Test build - [run #6](https://gpuci.gpuopenanalytics.com/job/gpuci/job/gpuci-build-environment/job/miniforge-cuda-test-build/6/)
- [x] Test images - [tag list](https://hub.docker.com/repository/docker/gpucitesting/miniforge-cuda-pr148/tags?page=1&ordering=last_updated)
- [x] Add CODEOWNERS file

### CODE REVIEW

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
Passing build - https://gpuci.gpuopenanalytics.com/job/gpuci/job/gpuci-build-environment/job/miniforge-cuda-test-build/7/
Test images - https://hub.docker.com/repository/docker/gpucitesting/miniforge-cuda-pr148/tags?page=1&ordering=last_updated

**Comment by mike-wendt** [comment]
rerun tests

**Review by dillon-cullinan — APPROVED** [review]

**Comment by mike-wendt** [comment]
rerun tests

**Pull request merged**
