### PR TITLE
Add 0.19 images to axis

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR adds the `0.19` images to the axis for CI.

### CODE REVIEW

**Review by dillon-cullinan — APPROVED** [review]

**Review by raydouglass — APPROVED** [review]

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Review by jolorunyomi — APPROVED** [review]

**Comment by mike-wendt** [comment]
All tests passed, merging

**Pull request merged**
