### PR TITLE
FIX Generate locales on Ubuntu

### PR DESCRIPTION
**Pull request by mike-wendt**
Install `locales` and generate `en_US.UTF-8` for Ubuntu images. This fixes the error message currently seen in Ubuntu images:
```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

**NOTE:** This also includes a tweak to `apt installs` where we now use `--no-install-recommends`

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests - new version of `gpuci-tools` should fix the random conda JSON errors we've seen

**Comment by mike-wendt** [comment]
Found some missing instances where `gpuci_retry_conda` wasn't being used and those areas were the same ones where builds were failing. This [commit](https://github.com/rapidsai/gpuci-build-environment/commit/84ab1944a32d55fbb2b030e7f88bfebb55e13f54) should fix that

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Pull request merged**
